In [1]:
import numpy as np

In [2]:
vetor_linha=np.array([1,2,3,4,5])

In [3]:
print(vetor_linha)

[1 2 3 4 5]


In [6]:
vetor_coluna=np.array([[1],[2],[3],[4],[5]])

In [7]:
print(vetor_coluna)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [8]:
matriz=np.array([[14,62,3],[44,5,61],[7,86,9]])

In [9]:
print(matriz)

[[14 62  3]
 [44  5 61]
 [ 7 86  9]]


In [10]:
np.linspace(0,20,num=5)

array([ 0.,  5., 10., 15., 20.])

In [11]:
np.random.randint(0,11,3)

array([6, 5, 6])

#n de linhas e colunas

In [12]:
print(matriz.shape)

(3, 3)


In [13]:
print(matriz.dtype)

int64


In [14]:
print(matriz.size)

9


In [15]:
print(matriz.ndim)

2


In [16]:
print(np.min(matriz))

3


In [17]:
print(np.max(matriz))

86


In [19]:
print(np.max(matriz,axis=0))

[44 86 61]


In [20]:
print(np.min(matriz,axis=0))

[7 5 3]


In [24]:
a = np.arange(6)

In [25]:
print(a)

[0 1 2 3 4 5]


In [26]:
b = a.reshape(3,2)

In [27]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [29]:
s = np.array([1,9,15,4])

In [30]:
print(s)

[ 1  9 15  4]


In [31]:
np.sort(s)

array([ 1,  4,  9, 15])

In [32]:
np.concatenate((a,s))

array([ 0,  1,  2,  3,  4,  5,  1,  9, 15,  4])

In [33]:
np.std(matriz)

29.5296461204668

In [34]:
np.percentile(a,10)

0.5

In [35]:
np.var(matriz)

871.9999999999999

In [36]:
matriz.T

array([[14, 44,  7],
       [62,  5, 86],
       [ 3, 61,  9]])

In [37]:
matriz1=np.array([[14,2,3],[48,6,8]])

In [38]:
matriz2=np.array([[1,21,3],[4,54,66]])

In [39]:
print(matriz1, matriz2)

[[14  2  3]
 [48  6  8]] [[ 1 21  3]
 [ 4 54 66]]


In [40]:
print(np.add(matriz1,matriz2))

[[15 23  6]
 [52 60 74]]


In [41]:
print(np.subtract(matriz1,matriz2))

[[ 13 -19   0]
 [ 44 -48 -58]]


In [42]:
print(matriz1*matriz2)

[[ 14  42   9]
 [192 324 528]]


In [43]:
print(matriz1.diagonal())

[14  6]


In [44]:
print(matriz1.diagonal(offset=1))

[2 8]


In [45]:
print(matriz1.diagonal(offset=-1))

[48]


In [46]:
print(np.linalg.inv(matriz1))

LinAlgError: Last 2 dimensions of the array must be square

In [47]:
matriz

array([[14, 62,  3],
       [44,  5, 61],
       [ 7, 86,  9]])

In [48]:
print(np.linalg.inv(matriz))

[[ 0.08719926  0.00502976 -0.06315701]
 [-0.00051974 -0.00176042  0.01210495]
 [-0.06285523  0.01290972  0.04456367]]


In [49]:
add_100=lambda i: i+100

In [50]:
_add_100=np.vectorize(add_100)

In [51]:
print(add_100)

<function <lambda> at 0x7f93d4960b80>


In [52]:
print(_add_100(matriz))

[[114 162 103]
 [144 105 161]
 [107 186 109]]


In [53]:
print(a)

[0 1 2 3 4 5]


In [54]:
print(np.where(a<4))

(array([0, 1, 2, 3]),)


In [55]:
print(np.where(a>2))

(array([3, 4, 5]),)


In [57]:
print(np.where(a==3))

(array([3]),)


In [58]:
print(np.where(a!=3))

(array([0, 1, 2, 4, 5]),)


In [61]:
print(np.where((a>2)&(a!=3)))

(array([4, 5]),)
